### ISSUE TITLE
Дефолтное значение

### ISSUE THREAD

**Issue by Jay416** [koorchik/js-validator-livr#10]
Привет :)
Можно добавить поддержку правил следующего вида:
```
  default_value: function (defaultValue) {
    return function (value, params, outputArr) {
      if (isNoValue(value)) outputArr.push(defaultValue);
    };
  }
``` 
то есть, если нет значения подставляем дефолтное...

**Comment by koorchik** [comment]
Да, будет добавлено на уровне спецификации - https://github.com/koorchik/LIVR/issues/12 . 
Войдет в следующий апдейт. Пока тикет закрываю, так как описано в новый версии спеки уже.
