### ISSUE TITLE
iso_date rule

### ISSUE THREAD

**Issue by SerikDM** [koorchik/js-validator-livr#11]
После строки
```javascript
d.setTime(d.getTime() + d.getTimezoneOffset() * 60 * 1000);
```
изменяется число на предыдущее. После чего проверка 
```javascript
d.getDate() == +matched[3]
```
не выполняется.

**Comment by koorchik** [comment]
Не понял, в чем конкретно баг?

**Comment by SerikDM** [comment]
Строка "2015-10-10" не проходит проверку.

**Comment by koorchik** [comment]
Спасибо. Сразу добавлю ссылку для репродюса - http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20date%3A%20'iso_date'%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%20date%3A%20'2015-10-10'%5Cn%7D%22%7D
