### ISSUE TITLE
list_of_different_objects ignores unknown objects

### ISSUE THREAD

**Issue by EviGL** [koorchik/js-validator-livr#17]
http://webbylab.github.io/livr-playground/#{%22rules%22%3A%22{\n%20%20%20%20order_id%3A%20[%27required%27%2C%20%27positive_integer%27]%2C\n%20%20%20%20products%3A%20[%27required%27%2C%20{%20%27list_of_different_objects%27%3A%20[\n%20%20%20%20%20%20%20%20product_type%2C%20{\n%20%20%20%20%20%20%20%20%20%20%20%20material%3A%20{\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product_type%3A%20%27required%27%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20material_id%3A%20[%27required%27%2C%20%27positive_integer%27]%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20quantity%3A%20[%27required%27%2C%20{%27min_number%27%3A%201}%20]%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20warehouse_id%3A%20%27positive_integer%27\n%20%20%20%20%20%20%20%20%20%20%20%20}%2C\n%20%20%20%20%20%20%20%20%20%20%20%20service%3A%20{\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product_type%3A%20%27required%27%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20[%27required%27%2C%20{%27max_length%27%3A%2020}%20]\n%20%20%20%20%20%20%20%20%20%20%20%20}\n%20%20%20%20%20%20%20%20}\n%20%20%20%20]}]\n}%22%2C%22data%22%3A%22{\n%20%20%20%20order_id%3A%2010455%2C\n%20%20%20%20products%3A%20[{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%201%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}%2C{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27ostrich%27%2C\n%20%20%20%20%20%20%20%20legs_count%3A2\n%20%20%20%20}%2C{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%205%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}%2C{\n%20%20%20%20%20%20%20%20product_type%3A%20%27service%27%2C\n%20%20%20%20%20%20%20%20name%3A%20%27Clean%20filter%27\n%20%20%20%20}]\n}%22}

Used example from readme. Invalid object types just get ignored. May be there's a way to limit this objects by adding something to the rules? Then this is not an issue.

**Comment by EviGL** [comment]
See 
{ 
        product_type: 'ostrich',
        legs_count:2
    }

**Comment by koorchik** [comment]
Yes. It is ok. One of the requirements to the validator is "Exclude all fields that do not have validation rules described". It is a security related issue. 

The simplest way to deal with this is to create custom rule. Moreover, In LIVR 2.0 there will be a rule "any_object" and you can write something like 

```
{products: { list_of: ['required', 'any_object'] }}
```

**Comment by koorchik** [comment]
I close the issue. But feel free to reopen if you still struggle with this issue in your app.
