### ISSUE TITLE
list_of_objects and list_of_different_objects have different behaviour on error

### ISSUE THREAD

**Issue by EviGL** [koorchik/js-validator-livr#18]
list_of_different_objects also returns "FORMAT_ERROR" in results array. This can lead to showing error messages on wrong objects in real apps. 

```
{
    "products": [
        "FORMAT_ERROR",
        {
            "quantity": "TOO_LOW"
        },
        null,
        null,
        null
    ]
}
```
With typical error-handling code this will show   "quantity": "TOO_LOW" error on the products[1], while the error is in products[0]

Examples in playground:
http://webbylab.github.io/livr-playground/#{%22rules%22%3A%22{\n%20%20%20%20order_id%3A%20[%27required%27%2C%20%27positive_integer%27]%2C\n%20%20%20%20products%3A%20[%20%27not_empty_list%27%2C%20{%20%27list_of_objects%27%3A%20{\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product_type%3A%20%27required%27%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20material_id%3A%20[%27required%27%2C%20%27positive_integer%27]%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20quantity%3A%20[%27required%27%2C%20{%27min_number%27%3A%201}%20]%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20warehouse_id%3A%20%27positive_integer%27\n%20%20%20%20%20%20%20%20%20%20%20%20}}]\n}%22%2C%22data%22%3A%22{\n%20%20%20%20order_id%3A%2010455%2C\n%20%20%20%20products%3A%20[{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%200%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}%2C{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%205%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}%2C{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%205%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}]\n}%22}

http://webbylab.github.io/livr-playground/#{%22rules%22%3A%22{\n%20%20%20%20order_id%3A%20[%27required%27%2C%20%27positive_integer%27]%2C\n%20%20%20%20products%3A%20[%27required%27%2C%20{%20%27list_of_different_objects%27%3A%20[\n%20%20%20%20%20%20%20%20product_type%2C%20{\n%20%20%20%20%20%20%20%20%20%20%20%20material%3A%20{\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product_type%3A%20%27required%27%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20material_id%3A%20[%27required%27%2C%20%27positive_integer%27]%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20quantity%3A%20[%27required%27%2C%20{%27min_number%27%3A%201}%20]%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20warehouse_id%3A%20%27positive_integer%27\n%20%20%20%20%20%20%20%20%20%20%20%20}%2C\n%20%20%20%20%20%20%20%20%20%20%20%20service%3A%20{\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product_type%3A%20%27required%27%2C\n%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20[%27required%27%2C%20{%27max_length%27%3A%2020}%20]\n%20%20%20%20%20%20%20%20%20%20%20%20}\n%20%20%20%20%20%20%20%20}\n%20%20%20%20]}]\n}%22%2C%22data%22%3A%22{\n%20%20%20%20order_id%3A%2010455%2C\n%20%20%20%20products%3A%20[123%2C{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%200%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}%2C{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%205%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}%2C{%20\n%20%20%20%20%20%20%20%20product_type%3A%20%27material%27%2C\n%20%20%20%20%20%20%20%20material_id%3A%20345%2C\n%20%20%20%20%20%20%20%20quantity%3A%20%205%2C\n%20%20%20%20%20%20%20%20warehouse_id%3A%2024\n%20%20%20%20}%2C{\n%20%20%20%20%20%20%20%20product_type%3A%20%27service%27%2C\n%20%20%20%20%20%20%20%20name%3A%20%27Clean%20filter%27\n%20%20%20%20}]\n}%22}

**Comment by koorchik** [comment]
FORMAT_ERROR - in most cases is related to developers error, not to users input error. I mean, if user has form then your code will pack into object and pass it. So, usually it is not possible for user pass primitive value instead of object, only developer can do this. But in this case FORMAT_ERROR makes sense.

I close the issue. Feel free to reopen if you still struggle with this issue in your app.

**Comment by koorchik** [comment]
One more way to solve the issue (will be available in next release) is to use "or" with "any_object" - [demo](http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7B%5Cn%20%20%20%20order_id%3A%20%5B'required'%2C%20'positive_integer'%5D%2C%5Cn%20%20%20%20products%3A%20%5B'required'%2C%20%7Bor%3A%20%5B%7B%20'list_of_different_objects'%3A%20%5B%5Cn%20%20%20%20%20%20%20%20product_type%2C%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20material%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product_type%3A%20'required'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20material_id%3A%20%5B'required'%2C%20'positive_integer'%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20quantity%3A%20%5B'required'%2C%20%7B'min_number'%3A%201%7D%20%5D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20warehouse_id%3A%20'positive_integer'%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20service%3A%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20product_type%3A%20'required'%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%5B'required'%2C%20%7B'max_length'%3A%2020%7D%20%5D%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%5D%7D%2C%20'any_object'%5D%7D%5D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20%20%20order_id%3A%2010455%2C%5Cn%20%20%20%20products%3A%20%5B123%2C%7B%20%5Cn%20%20%20%20%20%20%20%20product_type%3A%20'material'%2C%5Cn%20%20%20%20%20%20%20%20material_id%3A%20345%2C%5Cn%20%20%20%20%20%20%20%20quantity%3A%20%200%2C%5Cn%20%20%20%20%20%20%20%20warehouse_id%3A%2024%5Cn%20%20%20%20%7D%2C%7B%20%5Cn%20%20%20%20%20%20%20%20product_type%3A%20'material'%2C%5Cn%20%20%20%20%20%20%20%20material_id%3A%20345%2C%5Cn%20%20%20%20%20%20%20%20quantity%3A%20%205%2C%5Cn%20%20%20%20%20%20%20%20warehouse_id%3A%2024%5Cn%20%20%20%20%7D%2C%7B%20%5Cn%20%20%20%20%20%20%20%20product_type%3A%20'material'%2C%5Cn%20%20%20%20%20%20%20%20material_id%3A%20345%2C%5Cn%20%20%20%20%20%20%20%20quantity%3A%20%205%2C%5Cn%20%20%20%20%20%20%20%20warehouse_id%3A%2024%5Cn%20%20%20%20%7D%2C%7B%5Cn%20%20%20%20%20%20%20%20product_type%3A%20'service'%2C%5Cn%20%20%20%20%20%20%20%20name%3A%20'Clean%20filter'%5Cn%20%20%20%20%7D%5D%5Cn%7D%22%7D)  (demo will work in several days, after the update)
