### ISSUE TITLE
Array type rules

### ISSUE THREAD

**Issue by imatveev** [koorchik/js-validator-livr#20]
According to this [proposal](https://github.com/koorchik/LIVR/issues/14) the question arises: should the rules for arrays be added?

**Comment by koorchik** [comment]
What rules do you need?  Could you describe the use case?

**Comment by koorchik** [comment]
I guess it is a good idea to start implementing additional rules in a separate package. And some of them can migrate to core with time.

**Comment by koorchik** [comment]
I am going to add some of the rules we use in our projects to https://github.com/koorchik/js-livr-extra-rules

**Comment by imatveev** [comment]
That's not quite common use case, but for example: your API endpoint accepts array-type data in one of fields (e.g. { fields: ['first', 'second'] }), so sometimes you need to validate that array is passed to "fields" parameter and for example it has length of 2. At this time 'length_equal' rule is string-specific and throws "FORMAT_ERROR" for arrays. So we might have rules like ['array', 'array_length_equal'], etc. Is it good approach to implement those rules in a forked copy of https://github.com/koorchik/js-livr-extra-rules to have a possibility keep all additional rules synchronized? P.S It will be nice to have uuid validation rule too, it's quite common use case.

**Comment by koorchik** [comment]
I've started adding new rules to https://github.com/koorchik/js-livr-extra-rules. Now it has tests, basic structure and one rule ("ipv4") implemented
