### ISSUE TITLE
min_length for empty strings

### ISSUE THREAD

**Issue by chepiga1995** [koorchik/js-validator-livr#23]
https://github.com/koorchik/js-validator-livr/blob/4f265c46121333f2fee5c7057336e5faa34d8c27/lib/LIVR/Rules/String.js#L64

**Comment by DanielHreben** [comment]
@chepiga1995 It's expected behavior, use "required" or "not_empty" rules to disable empty strings.

**Comment by chepiga1995** [comment]
But what should I do if the field is optional?

**Comment by DanielHreben** [comment]
`[ 'not_empty', {min_length: 10} ]` i guess.
It will disable empty strings but the field still will be optional.

**Comment by chepiga1995** [comment]
ok, thanks
