### ISSUE TITLE
rule with multiple arguments

### ISSUE THREAD

**Issue by DenniLa2** [koorchik/js-validator-livr#25]
Подскажите, допустим есть js-объект типа {email: 'em@a.il, useEmail: false}. Есть ли возможность написать правило, в которое на вход попадает два поля: email и useEmail? Т.е. мне нужно валидировать емеил только, если он используется.
И спасибо за валидатор! Он развязал руки и упростил разработку ))

**Comment by koorchik** [comment]
Вторым аргументом всегда приходит объект со всеми полями, вот пример https://github.com/koorchik/js-validator-livr/blob/master/lib/LIVR/Rules/Special.js#L21
