### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by DenniLa2** [koorchik/js-validator-livr#26]
Поддерживает ли JS реализация IE11? 
![image](https://user-images.githubusercontent.com/9018493/32891394-0e942968-cadb-11e7-9f59-00fb6007cc8c.png)

**Comment by koorchik** [comment]
Да, баг. Нужно будет добавить свою реализацию isInterger

**Comment by DenniLa2** [comment]
Спасибо за ответ! Когда Вы, примерно, планируете это сделать?

**Comment by koorchik** [comment]
Обновляем комплект тестов как раз в спеке, думаем до конца недели новые релизы сделать

**Comment by denis111** [comment]
Another IE11 failure occurs when using LIVR.js from npm module (at least with Angular), IE11 doesn't support object property shorthand:
module.exports = { Validator, rules, util };
should be
module.exports = { Validator: Validator, rules: rules, util: util };

**Comment by koorchik** [comment]
The best approach here is to use it with Babel and bundle with webpack or parcel.

**Comment by denis111** [comment]
No idea how to it in Angular 8 project but thanks, I'll try it.

**Comment by koorchik** [comment]
I close the issue due to no activities for a long time.
Please, fill free to reopen with a comment if the issue is still actual.
