### ISSUE TITLE
В правилах-фильтрах переопределяется undefined

### ISSUE THREAD

**Issue by sameoldmadness** [koorchik/js-validator-livr#3]
https://github.com/koorchik/js-validator-livr/blob/master/lib/LIVR/Rules/Filters.js#L7

Насколько я понял, вторым аргументом передаётся объект с данными. А значит, выражение `value === undefined` всегда будет ложным.

**Comment by koorchik** [comment]
Спасибо, исправим. Получается, что фильтры применяются ко всем значениям. В процессе портирования перловой реализация пролезла не работающая в JS идиома.
