### ISSUE TITLE
Утилиты для написания собственных правил

### ISSUE THREAD

**Issue by sameoldmadness** [koorchik/js-validator-livr#4]
Почти во всех правилах нужно следующее:

```js
if (value === undefined || value === null || value === '' ) return;
if (!util.isNumberOrString(value)) return 'FORMAT_ERROR';
value += '';
```

Может, добавить методы `utils.isNotEmpty` и `utils.numToString`, а ссылку на `utils` сделать доступной снаружи?

**Comment by koorchik** [comment]
Done. Utils are available from outside.
