### ISSUE TITLE
Правило optional

### ISSUE THREAD

**Issue by sameoldmadness** [koorchik/js-validator-livr#5]
Можно добавить правило-пустышку `optional`, чтобы указывать в схеме необязательные поля, не требующие валидации.

```json
{
  "name": "optional", 
}
```

Сейчас приходится делать так:

```json
{
  "name": [], 
}
```

**Comment by koorchik** [comment]
"optional" звучит неоднозначно. По сути, может быть ['required', 'optional'] (выглядит нелогично), что обозначает обязательное значение любого типа (не требующее валидации). Логично назвать правило "any" - любой тип данных. 

Выглядеть будет так:

```javascript
{
   "name": "any"
}
```

```javascript
{
   "payload": ["required", "any"]
}
```

**Comment by koorchik** [comment]
Но пока не уверен, что это правило должно быть в спеке, поскольку поля без валидации это редкий случай (всегда хоть минимальная валидация, но нужна). "  Кроме того, его легко зарегистрировать самому:

```javascript
LIVR.Validator.registerDefaultRules({ any: function() {
     return function() {}
});
```

**Comment by sameoldmadness** [comment]
Безусловно, легко.

Вопрос концептуальный: поощряет ли спека определение схемы целиком, в том числе с упоминанием невалидируемых полей.

**Comment by koorchik** [comment]
Спека поощряет, в связи с этим и удаляются все поля без валидации. То есть, схема должна определяться полностью, но вопрос в том, бывают ли поля совсем без валидации. 
Например, правило "any" пропускает любой тип, это может быть строки, массив, объект, null и так далее. На практике же, обычно мы хотим, например, любую строку, но не объект и так далее.

Но пока мы собираем предложения для LIVR 0.5 - https://github.com/koorchik/LIVR/compare/v0.5 ("any" уже добавил)

**Comment by sameoldmadness** [comment]
Супер, это обсуждение закрываю.
