### ISSUE TITLE
Describe a rule for an array

### ISSUE THREAD

**Issue by i474232898** [koorchik/js-validator-livr#50]
What would be the rule to describe an array? In all examples that I've found arrays exists only as a property in some object. How can we describe an array not inside some object ?
like:
const input = [{a: 1, b: 2}, {a: 3, b: 4}];

**Comment by koorchik** [comment]
Yes, it is correct. The only way to validate the array is to put it inside an object. So, it will look like

```js
const input = [1, 2 ,3];
const validator = new LIVR.Validator({
     data: { 'list_of': [ 'required',  'positive_integer' ] }
});
const result = validator.validate({data: input});
```

If is is a very common case, then  having a custom wrapper around the validator can be beneficial

**Comment by i474232898** [comment]
Thank you!
