### ISSUE TITLE
Некорректные сравнения для логического типа

### ISSUE THREAD

**Issue by SDSWanderer** [koorchik/js-validator-livr#6]
Реализация считает что `true != true` 
Пример:
http://webbylab.github.io/livr-playground/#%7B%22rules%22%3A%22%7Btest%3A%20%7Bone_of%3A%5Btrue%2C%20false%5D%7D%7D%22%2C%22data%22%3A%22%7Btest%3A%20true%7D%22%7D

**Comment by koorchik** [comment]
Fixed
