### ISSUE TITLE
Python bug with one_of rule

### ISSUE THREAD

**Issue by siavolt** [koorchik/js-validator-livr#9]
http://livr-playground.tk/#%7B%22rules%22%3A%22%7B%5Cn%20%20flag%3A%20%7Bone_of%3A%20%5B%5C%22false%5C%22%5D%7D%5Cn%7D%22%2C%22data%22%3A%22%7B%5Cn%20%20flag%3A%20%5B%5D%5Cn%7D%22%7D

**Comment by koorchik** [comment]
Closed as duplicate for https://github.com/asholok/python-validator-livr/issues/7
